name: github_trending
description: Flutter for Web example.

version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  url_launcher: ^5.1.4
  url_launcher_web: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  image_path: "assets/images/icon-ios.png"
  android: false
  ios: true

flutter:
  uses-material-design: true
